export const GAME_DATA = [
  {
    id: 1,
    homeTeam: "Vanderbilt",
    awayTeam: "Tennessee",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "45.5",
    ouPayout: 2,
    spreadHome: "Vanderbilt -6.5",
    spreadAway: "Tennessee +6.5",
    spreadPayout: 2,
    moneyLineHome: "Vanderbilt -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Tennessee +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Vanderbilt QB passes for over 250 yards", payout: 4 },
      { name: "Tennesee RB rushes for under 250 yards", payout: 3 },
      { name: "Vanderbilt scores first touchdown", payout: 2 },
    ],
  },
  {
    id: 2,
    homeTeam: "Oklahoma",
    awayTeam: "Texas",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Oklahoma -6.5",
    spreadAway: "Texas +6.5",
    spreadPayout: 2,
    moneyLineHome: "Oklahoma -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Texas +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Oklahoma QB passes for over 250 yards", payout: 4 },
      { name: "Texas RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 3,
    homeTeam: "Alabama",
    awayTeam: "Auburn",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Alabama -6.5",
    spreadAway: "Auburn +6.5",
    spreadPayout: 2,
    moneyLineHome: "Alabama -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Auburn +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Alabama QB passes for over 250 yards", payout: 4 },
      { name: "Auburn RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 4,
    homeTeam: "Texas A&M",
    awayTeam: "LSU",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Texas A&M -6.5",
    spreadAway: "LSU +6.5",
    spreadPayout: 2,
    moneyLineHome: "Texas A&M -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "LSU +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Texas A&M QB passes for over 250 yards", payout: 4 },
      { name: "LSU RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 5,
    homeTeam: "Ole Miss",
    awayTeam: "Mississippi St",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Ole Miss -6.5",
    spreadAway: "Mississippi St +6.5",
    spreadPayout: 2,
    moneyLineHome: "Ole Miss -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Mississippi St +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Ole Miss QB passes for over 250 yards", payout: 4 },
      { name: "Mississippi St RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 6,
    homeTeam: "Missouri",
    awayTeam: "Arkansas",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Missouri -6.5",
    spreadAway: "Arkansas +6.5",
    spreadPayout: 2,
    moneyLineHome: "Missouri -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Arkansas +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Missouri QB passes for over 250 yards", payout: 4 },
      { name: "Arkansas RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 7,
    homeTeam: "Florida",
    awayTeam: "Georgia",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "Florida -6.5",
    spreadAway: "Georgia +6.5",
    spreadPayout: 2,
    moneyLineHome: "Florida -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Georgia +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "Florida QB passes for over 250 yards", payout: 4 },
      { name: "Georgia RB rushes for under 250 yards", payout: 3 },
    ],
  },
  {
    id: 8,
    homeTeam: "S Carolina",
    awayTeam: "Kentucky",
    homeRecord: "0-0",
    awayRecord: "0-0",
    date: "9/14",
    time: "6:00 PM",
    ou: "35.5",
    ouPayout: 2,
    spreadHome: "S Carolina -6.5",
    spreadAway: "Kentucky +6.5",
    spreadPayout: 2,
    moneyLineHome: "S Carolina -150",
    moneyLineHomePayout: 1.5,
    moneyLineAway: "Kentucky +150",
    moneyLineAwayPayout: 2.5,
    propBets: [
      { name: "S Carolina QB passes for over 250 yards", payout: 4 },
      { name: "Kentucky RB rushes for under 250 yards", payout: 3 },
    ],
  },
];
