export const GAME_DATA = [
    { id: 1, homeTeam: "Vanderbilt", awayTeam: "Tennessee", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Vanderbilt -6.5", spreadAway: "Tennessee +6.5", moneyLineHome: "Vanderbilt -150", moneyLineAway: "Tennessee +150" },
    { id: 2, homeTeam: "Oklahoma", awayTeam: "Texas", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Oklahoma -6.5", spreadAway: "Texas +6.5", moneyLineHome: "Oklahoma -150", moneyLineAway: "Texas +150" },
    { id: 3, homeTeam: "Alabama", awayTeam: "Auburn", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Alabama -6.5", spreadAway: "Auburn +6.5", moneyLineHome: "Alabama -150", moneyLineAway: "Auburn +150" },
    { id: 4, homeTeam: "Texas A&M", awayTeam: "LSU", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Texas A&M -6.5", spreadAway: "LSU +6.5", moneyLineHome: "Texas A&M -150", moneyLineAway: "LSU +150" },
    { id: 5, homeTeam: "Ole Miss", awayTeam: "Mississippi St", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Ole Miss -6.5", spreadAway: "Mississippi St +6.5", moneyLineHome: "Ole Miss -150", moneyLineAway: "Mississippi St +150" },
    { id: 6, homeTeam: "Missouri", awayTeam: "Arkansas", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Missouri -6.5", spreadAway: "Arkansas +6.5", moneyLineHome: "Missouri -150", moneyLineAway: "Arkansas +150" },
    { id: 7, homeTeam: "Florida", awayTeam: "Georgia", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "Florida -6.5", spreadAway: "Georgia +6.5", moneyLineHome: "Florida -150", moneyLineAway: "Georgia +150" },
    { id: 8, homeTeam: "South Carolina", awayTeam: "Kentucky", homeRecord: "0-0", awayRecord: "0-0", date: "9/14", time: "6:00 PM", ou: "35.5", spreadHome: "South Carolina -6.5", spreadAway: "Kentucky +6.5", moneyLineHome: "South Carolina -150", moneyLineAway: "Kentucky +150" },
  ];