export const nameMap = {
  // "Alabama": "alabama",
  // "Penn State": "penn_state",
  // "Mississippi State": "mississippi_state",

  "Boston College": "boston_college",
  "California": "california",
  "Clemson": "clemson",
  "Duke": "duke",
  "Florida St": "florida_state",
  "Georgia Tech": "georgia_tech",
  "Louisville": "louisville",
  "Miami": "miami",
  "NC State": "nc_state",
  "North Carolina": "north_carolina",
  "Pitt": "pitt",
  "SMU": "smu",
  "Stanford": "stanford",
  "Syracuse": "syracuse",
  "Virginia": "virginia",
  "Virginia Tech": "virginia_tech",
  "Wake Forest": "wake_forest",
  "Arizona St": "arizona_state",
  "Arizona": "arizona",
  "BYU": "byu",
  "Baylor": "baylor",
  "Cincinnati": "cincinnati",
  "Colorado": "colorado",
  "Houston": "houston",
  "Iowa State": "iowa_state",
  "Kansas": "kansas",
  "Kansas St": "kansas_state",
  "Oklahoma St": "oklahoma_state",
  "TCU": "tcu",
  "Texas Tech": "texas_tech",
  "UCF": "ucf",
  "Utah": "utah",
  "West Virginia": "west_virginia",
  "Illinois": "illinois",
  "Indiana": "indiana",
  "Iowa": "iowa",
  "Maryland": "maryland",
  "Michigan St": "michigan_state",
  "Michigan": "michigan",
  "Minnesota": "minnesota",
  "Nebraska": "nebraska",
  "Northwestern": "northwestern",
  "Ohio State": "ohio_state",
  "Oregon": "oregon",
  "Penn State": "penn_state",
  "Purdue": "purdue",
  "Rutgers": "rutgers",
  "UCLA": "ucla",
  "USC": "usc",
  "Washington": "washington",
  "Wisconsin": "wisconsin",
  "Notre Dame": "notre_dame",
  "Alabama": "alabama",
  "Arkansas": "arkansas",
  "Auburn": "auburn",
  "Florida": "florida",
  "Georgia": "georgia",
  "Kentucky": "kentucky",
  "LSU": "lsu",
  "Mississippi St": "mississippi_state",
  "Missouri": "missouri",
  "Oklahoma": "oklahoma",
  "Ole Miss": "ole_miss",
  "South Carolina": "south_carolina",
  "Tennessee": "tennessee",
  "Texas A&M": "texas_am",
  "Texas": "texas",
  "Vanderbilt": "vanderbilt"
  
};

export const logoMap = {
  boston_college: require('@/assets/teamLogos/boston_college.png'),
  california: require('@/assets/teamLogos/california.png'),
  clemson: require('@/assets/teamLogos/clemson.png'),
  duke: require('@/assets/teamLogos/duke.png'),
  florida_state: require('@/assets/teamLogos/florida_state.png'),
  georgia_tech: require('@/assets/teamLogos/georgia_tech.png'),
  louisville: require('@/assets/teamLogos/louisville.png'),
  miami: require('@/assets/teamLogos/miami.png'),
  nc_state: require('@/assets/teamLogos/nc_state.png'),
  north_carolina: require('@/assets/teamLogos/north_carolina.png'),
  pitt: require('@/assets/teamLogos/pitt.png'),
  smu: require('@/assets/teamLogos/smu.png'),
  stanford: require('@/assets/teamLogos/stanford.png'),
  syracuse: require('@/assets/teamLogos/syracuse.png'),
  virginia: require('@/assets/teamLogos/virginia.png'),
  virginia_tech: require('@/assets/teamLogos/virginia_tech.png'),
  wake_forest: require('@/assets/teamLogos/wake_forest.png'),
  arizona_state: require('@/assets/teamLogos/arizona_state.png'),
  arizona: require('@/assets/teamLogos/arizona.png'),
  byu: require('@/assets/teamLogos/byu.png'),
  baylor: require('@/assets/teamLogos/baylor.png'),
  cincinnati: require('@/assets/teamLogos/cincinnati.png'),
  colorado: require('@/assets/teamLogos/colorado.png'),
  houston: require('@/assets/teamLogos/houston.png'),
  iowa_state: require('@/assets/teamLogos/iowa_state.png'),
  kansas: require('@/assets/teamLogos/kansas.png'),
  kansas_state: require('@/assets/teamLogos/kansas_state.png'),
  oklahoma_state: require('@/assets/teamLogos/oklahoma_state.png'),
  tcu: require('@/assets/teamLogos/tcu.png'),
  texas_tech: require('@/assets/teamLogos/texas_tech.png'),
  ucf: require('@/assets/teamLogos/ucf.png'),
  utah: require('@/assets/teamLogos/utah.png'),
  west_virginia: require('@/assets/teamLogos/west_virginia.png'),
  illinois: require('@/assets/teamLogos/illinois.png'),
  indiana: require('@/assets/teamLogos/indiana.png'),
  iowa: require('@/assets/teamLogos/iowa.png'),
  maryland: require('@/assets/teamLogos/maryland.png'),
  michigan_state: require('@/assets/teamLogos/michigan_state.png'),
  michigan: require('@/assets/teamLogos/michigan.png'),
  minnesota: require('@/assets/teamLogos/minnesota.png'),
  nebraska: require('@/assets/teamLogos/nebraska.png'),
  northwestern: require('@/assets/teamLogos/northwestern.png'),
  ohio_state: require('@/assets/teamLogos/ohio_state.png'),
  oregon: require('@/assets/teamLogos/oregon.png'),
  penn_state: require('@/assets/teamLogos/penn_state.png'),
  purdue: require('@/assets/teamLogos/purdue.png'),
  rutgers: require('@/assets/teamLogos/rutgers.png'),
  ucla: require('@/assets/teamLogos/ucla.png'),
  usc: require('@/assets/teamLogos/usc.png'),
  washington: require('@/assets/teamLogos/washington.png'),
  wisconsin: require('@/assets/teamLogos/wisconsin.png'),
  notre_dame: require('@/assets/teamLogos/notre_dame.png'),
  alabama: require('@/assets/teamLogos/alabama.png'),
  arkansas: require('@/assets/teamLogos/arkansas.png'),
  auburn: require('@/assets/teamLogos/auburn.png'),
  florida: require('@/assets/teamLogos/florida.png'),
  georgia: require('@/assets/teamLogos/georgia.png'),
  kentucky: require('@/assets/teamLogos/kentucky.png'),
  lsu: require('@/assets/teamLogos/lsu.png'),
  mississippi_state: require('@/assets/teamLogos/mississippi_state.png'),
  missouri: require('@/assets/teamLogos/missouri.png'),
  oklahoma: require('@/assets/teamLogos/oklahoma.png'),
  ole_miss: require('@/assets/teamLogos/ole_miss.png'),
  south_carolina: require('@/assets/teamLogos/south_carolina.png'),
  tennessee: require('@/assets/teamLogos/tennessee.png'),
  texas_am: require('@/assets/teamLogos/texas_am.png'),
  texas: require('@/assets/teamLogos/texas.png'),
  vanderbilt: require('@/assets/teamLogos/vanderbilt.png'),
};