// export const nameMap = {
//   "Boston College": "boston_college",
//   "California": "california",
//   "Clemson": "clemson",
//   "Duke": "duke",
//   "Florida St": "florida_st",
//   "Georgia Tech": "georgia_tech",
//   "Louisville": "louisville",
//   "Miami": "miami",
//   "NC State": "nc_state",
//   "North Carolina": "north_carolina",
//   "Pitt": "pitt",
//   "SMU": "smu",
//   "Stanford": "stanford",
//   "Syracuse": "syracuse",
//   "Virginia": "virginia",
//   "Virginia Tech": "virginia_tech",
//   "Wake Forest": "wake_forest",
//   "Arizona St": "arizona_st",
//   "Arizona": "arizona",
//   "BYU": "byu",
//   "Baylor": "baylor",
//   "Cincinnati": "cincinnati",
//   "Colorado": "colorado",
//   "Houston": "houston",
//   "Iowa State": "iowa_state",
//   "Kansas": "kansas",
//   "Kansas St": "kansas_st",
//   "Oklahoma St": "oklahoma_st",
//   "TCU": "tcu",
//   "Texas Tech": "texas_tech",
//   "UCF": "ucf",
//   "Utah": "utah",
//   "West Virginia": "west_virginia",
//   "Illinois": "illinois",
//   "Indiana": "indiana",
//   "Iowa": "iowa",
//   "Maryland": "maryland",
//   "Michigan St": "michigan_st",
//   "Michigan": "michigan",
//   "Minnesota": "minnesota",
//   "Nebraska": "nebraska",
//   "Northwestern": "northwestern",
//   "Ohio State": "ohio_state",
//   "Oregon": "oregon",
//   "Penn State": "penn_state",
//   "Purdue": "purdue",
//   "Rutgers": "rutgers",
//   "UCLA": "ucla",
//   "USC": "usc",
//   "Washington": "washington",
//   "Wisconsin": "wisconsin",
//   "Notre Dame": "notre_dame",
//   "Alabama": "alabama",
//   "Arkansas": "arkansas",
//   "Auburn": "auburn",
//   "Florida": "florida",
//   "Georgia": "georgia",
//   "Kentucky": "kentucky",
//   "LSU": "lsu",
//   "Mississippi St": "mississippi_state",
//   "Missouri": "missouri",
//   "Oklahoma": "oklahoma",
//   "Ole Miss": "ole_miss",
//   "South Carolina": "south_carolina",
//   "Tennessee": "tennessee",
//   "Texas A&M": "texas_am",
//   "Texas": "texas",
//   "Vanderbilt": "vanderbilt"
// };

// export const logoMap = {
//   boston_college: require('@/assets/teamLogos/boston_college.png'),
//   california: require('@/assets/teamLogos/california.png'),
//   clemson: require('@/assets/teamLogos/clemson.png'),
//   duke: require('@/assets/teamLogos/duke.png'),
//   florida_st: require('@/assets/teamLogos/florida_st.png'),
//   georgia_tech: require('@/assets/teamLogos/georgia_tech.png'),
//   louisville: require('@/assets/teamLogos/louisville.png'),
//   miami: require('@/assets/teamLogos/miami.png'),
//   nc_state: require('@/assets/teamLogos/nc_state.png'),
//   north_carolina: require('@/assets/teamLogos/north_carolina.png'),
//   pitt: require('@/assets/teamLogos/pitt.png'),
//   smu: require('@/assets/teamLogos/smu.png'),
//   stanford: require('@/assets/teamLogos/stanford.png'),
//   syracuse: require('@/assets/teamLogos/syracuse.png'),
//   virginia: require('@/assets/teamLogos/virginia.png'),
//   virginia_tech: require('@/assets/teamLogos/virginia_tech.png'),
//   wake_forest: require('@/assets/teamLogos/wake_forest.png'),
//   arizona_st: require('@/assets/teamLogos/arizona_st.png'),
//   arizona: require('@/assets/teamLogos/arizona.png'),
//   byu: require('@/assets/teamLogos/byu.png'),
//   baylor: require('@/assets/teamLogos/baylor.png'),
//   cincinnati: require('@/assets/teamLogos/cincinnati.png'),
//   colorado: require('@/assets/teamLogos/colorado.png'),
//   houston: require('@/assets/teamLogos/houston.png'),
//   iowa_state: require('@/assets/teamLogos/iowa_state.png'),
//   kansas: require('@/assets/teamLogos/kansas.png'),
//   kansas_st: require('@/assets/teamLogos/kansas_st.png'),
//   oklahoma_st: require('@/assets/teamLogos/oklahoma_st.png'),
//   tcu: require('@/assets/teamLogos/tcu.png'),
//   texas_tech: require('@/assets/teamLogos/texas_tech.png'),
//   ucf: require('@/assets/teamLogos/ucf.png'),
//   utah: require('@/assets/teamLogos/utah.png'),
//   west_virginia: require('@/assets/teamLogos/west_virginia.png'),
//   illinois: require('@/assets/teamLogos/illinois.png'),
//   indiana: require('@/assets/teamLogos/indiana.png'),
//   iowa: require('@/assets/teamLogos/iowa.png'),
//   maryland: require('@/assets/teamLogos/maryland.png'),
//   michigan_st: require('@/assets/teamLogos/michigan_st.png'),
//   michigan: require('@/assets/teamLogos/michigan.png'),
//   minnesota: require('@/assets/teamLogos/minnesota.png'),
//   nebraska: require('@/assets/teamLogos/nebraska.png'),
//   northwestern: require('@/assets/teamLogos/northwestern.png'),
//   ohio_state: require('@/assets/teamLogos/ohio_state.png'),
//   oregon: require('@/assets/teamLogos/oregon.png'),
//   penn_state: require('@/assets/teamLogos/penn_state.png'),
//   purdue: require('@/assets/teamLogos/purdue.png'),
//   rutgers: require('@/assets/teamLogos/rutgers.png'),
//   ucla: require('@/assets/teamLogos/ucla.png'),
//   usc: require('@/assets/teamLogos/usc.png'),
//   washington: require('@/assets/teamLogos/washington.png'),
//   wisconsin: require('@/assets/teamLogos/wisconsin.png'),
//   notre_dame: require('@/assets/teamLogos/notre_dame.png'),
//   alabama: require('@/assets/teamLogos/alabama.png'),
//   arkansas: require('@/assets/teamLogos/arkansas.png'),
//   auburn: require('@/assets/teamLogos/auburn.png'),
//   florida: require('@/assets/teamLogos/florida.png'),
//   georgia: require('@/assets/teamLogos/georgia.png'),
//   kentucky: require('@/assets/teamLogos/kentucky.png'),
//   lsu: require('@/assets/teamLogos/lsu.png'),
//   mississippi_state: require('@/assets/teamLogos/mississippi_state.png'),
//   missouri: require('@/assets/teamLogos/missouri.png'),
//   oklahoma: require('@/assets/teamLogos/oklahoma.png'),
//   ole_miss: require('@/assets/teamLogos/ole_miss.png'),
//   south_carolina: require('@/assets/teamLogos/south_carolina.png'),
//   tennessee: require('@/assets/teamLogos/tennessee.png'),
//   texas_am: require('@/assets/teamLogos/texas_am.png'),
//   texas: require('@/assets/teamLogos/texas.png'),
//   vanderbilt: require('@/assets/teamLogos/vanderbilt.png'),
// };

export const nameMap = {
  "Abilene Chrstn": "abilene_chrstn",
  "Air Force": "air_force",
  "Akron": "akron",
  "Alabama A&M": "alabama_am",
  "Alabama St": "alabama_st",
  "Alabama": "alabama",
  "Alcorn St": "alcorn_st",
  "App State": "app_state",
  "AR-Pine Bluff": "ar_pine_bluff",
  "Arizona St": "arizona_st",
  "Arizona": "arizona",
  "Arkansas St": "arkansas_st",
  "Arkansas": "arkansas",
  "Army": "army",
  "Auburn": "auburn",
  "Austin Peay": "austin_peay",
  "Ball State": "ball_state",
  "Baylor": "baylor",
  "Bethune": "bethune",
  "Boise St": "boise_st",
  "Boston College": "boston_college",
  "Bowling Green": "bowling_green",
  "Brown": "brown",
  "Bryant": "bryant",
  "Bucknell": "bucknell",
  "Buffalo": "buffalo",
  "Butler": "butler",
  "BYU": "byu",
  "C Arkansas": "c_arkansas",
  "C Connecticut": "c_connecticut",
  "C Michigan": "c_michigan",
  "Cal Poly": "cal_poly",
  "California": "california",
  "Campbell": "campbell",
  "Charleston So": "charleston_so",
  "Charlotte": "charlotte",
  "Chattanooga": "chattanooga",
  "Cincinnati": "cincinnati",
  "Clemson": "clemson",
  "Coastal": "coastal",
  "Colgate": "colgate",
  "Colorado St": "colorado_st",
  "Colorado": "colorado",
  "Columbia": "columbia",
  "Cornell": "cornell",
  "Dartmouth": "dartmouth",
  "Davidson": "davidson",
  "Dayton": "dayton",
  "Delaware St": "delaware_st",
  "Delaware": "delaware",
  "Drake": "drake",
  "Duke": "duke",
  "Duquesne": "duquesne",
  "E Illinois": "e_illinois",
  "E Kentucky": "e_kentucky",
  "E Michigan": "e_michigan",
  "E Texas A&M": "e_texas_am",
  "E Washington": "e_washington",
  "East Carolina": "east_carolina",
  "Elon": "elon",
  "ETSU": "ETSU",
  "FAU": "fau",
  "FIU": "fiu",
  "Florida A&M": "florida_am",
  "Florida St": "florida_st",
  "Florida": "florida",
  "Fordham": "fordham",
  "Fresno St": "fresno_st",
  "Furman": "furman",
  "GA Southern": "ga_southern",
  "Gardner-Webb": "gardner_webb",
  "Georgetown": "georgetown",
  "Georgia St": "georgia_st",
  "Georgia Tech": "georgia_tech",
  "Georgia": "georgia",
  "Grambling": "grambling",
  "Hampton": "hampton",
  "Harvard": "harvard",
  "Hawai’i": "hawaii",
  "Holy Cross": "holy_cross",
  "Hou Christian": "hou_christian",
  "Houston": "houston",
  "Howard": "howard",
  "Idaho St": "idaho_st",
  "Idaho": "idaho",
  "Illinois St": "illinois_st",
  "Illinois": "illinois",
  "Incarnate Word": "incarnate_word",
  "Indiana St": "indiana_st",
  "Indiana": "indiana",
  "Iowa State": "iowa_state",
  "Iowa": "iowa",
  "Jackson St": "jackson_st",
  "James Madison": "james_madison",
  "Jax State": "jax_state",
  "Kansas St": "kansas_st",
  "Kansas": "kansas",
  "Kennesaw St": "kennesaw_st",
  "Kent State": "kent_state",
  "Kentucky": "kentucky",
  "Lafayette": "lafayette",
  "Lamar": "lamar",
  "Lehigh": "lehigh",
  "Liberty": "liberty",
  "Lindenwood": "lindenwood",
  "Long Island": "long_island",
  "Louisiana Tech": "louisiana_tech",
  "Louisiana": "louisiana",
  "Louisville": "louisville",
  "LSU": "lsu",
  "Maine": "maine",
  "Marist": "marist",
  "Marshall": "marshall",
  "Maryland": "maryland",
  "McNeese": "mcneese",
  "Memphis": "memphis",
  "Mercer": "mercer",
  "Merrimack": "merrimack",
  "Miami": "miami",
  "Miami OH": "miami_oh",
  "Michigan St": "michigan_st",
  "Michigan": "michigan",
  "Minnesota": "minnesota",
  "Miss Valley St": "miss_valley_st",
  "Mississippi St": "mississippi_st",
  "Missouri St": "missouri_st",
  "Missouri": "missouri",
  "Monmouth": "monmouth",
  "Montana St": "montana_st",
  "Montana": "montana",
  "Morehead St": "morehead_st",
  "Morgan St": "morgan_st",
  "MTSU": "mtsu",
  "Murray St": "murray_st",
  "N Arizona": "n_arizona",
  "N Colorado": "n_colorado",
  "N Dakota St": "n_dakota_st",
  "N Illinois": "n_illinois",
  "Navy": "navy",
  "NC A&T": "nc_at",
  "NC Central": "nc_central",
  "NC State": "nc_state",
  "Nebraska": "nebraska",
  "Nevada": "nevada",
  "New Hampshire": "new_hampshire",
  "New Mexico": "new_mexico",
  "New Mexico St": "new_mexico_st",
  "Nicholls": "nicholls",
  "Norfolk St": "norfolk_st",
  "North Alabama": "north_alabama",
  "North Carolina": "north_carolina",
  "North Dakota": "north_dakota",
  "North Texas": "north_texas",
  "Northern Iowa": "northern_iowa",
  "Northwestern": "northwestern",
  "Notre Dame": "notre_dame",
  "N'Western St": "nwestern_st",
  "Ohio": "ohio",
  "Ohio State": "ohio_state",
  "Oklahoma St": "oklahoma_st",
  "Oklahoma": "oklahoma",
  "Old Dominion": "old_dominion",
  "Ole Miss": "ole_miss",
  "Oregon St": "oregon_st",
  "Oregon": "oregon",
  "Penn State": "penn_state",
  "Penn": "penn",
  "Pitt": "pitt",
  "Portland St": "portland_st",
  "Prairie View": "prairie_view",
  "Presbyterian": "presbyterian",
  "Princeton": "princeton",
  "Purdue": "purdue",
  "Rhode Island": "rhode_island",
  "Rice": "rice",
  "Richmond": "richmond",
  "Robert Morris": "robert_morris",
  "Rutgers": "rutgers",
  "S Illinois": "s_illinois",
  "Sacramento St": "sacramento_st",
  "Sacred Heart": "sacred_heart",
  "Sam Houston": "sam_houston",
  "Samford": "samford",
  "San Diego St": "san_diego_st",
  "San Diego": "san_diego",
  "San José St": "san_jose_st",
  "SC State": "sc_state",
  "SE Louisiana": "se_louisiana",
  "SE Missouri": "se_missouri",
  "SF Austin": "sf_austin",
  "SMU": "smu",
  "South Alabama": "south_alabama",
  "South Carolina": "south_carolina",
  "S Dakota St": "s_dakota_st",
  "South Dakota": "south_dakota",
  "South Florida": "south_florida",
  "Southern Miss": "southern_miss",
  "Southern Utah": "southern_utah",
  "Southern": "southern",
  "St Francis PA": "st_francis_pa",
  "St Thomas (MN)": "st_thomas_mn",
  "Stanford": "stanford",
  "Stetson": "stetson",
  "Stonehill": "stonehill",
  "Stony Brook": "stony_brook",
  "Syracuse": "syracuse",
  "Tarleton St": "tarleton_st",
  "TCU": "tcu",
  "Temple": "temple",
  "Tennessee St": "tennessee_st",
  "Tennessee Tech": "tennessee_tech",
  "Tennessee": "tennessee",
  "Texas A&M": "texas_am",
  "Texas Southern": "texas_southern",
  "Texas St": "texas_st",
  "Texas Tech": "texas_tech",
  "Texas": "texas",
  "The Citadel": "the_citadel",
  "Toledo": "toledo",
  "Towson": "towson",
  "Troy": "troy",
  "Tulane": "tulane",
  "Tulsa": "tulsa",
  "UAB": "uab",
  "UAlbany": "ualbany",
  "UC Davis": "uc_davis",
  "UCF": "ucf",
  "UCLA": "ucla",
  "UConn": "uconn",
  "UL Monroe": "ul_monroe",
  "UMass": "umass",
  "UNLV": "unlv",
  "USC": "usc",
  "UT Martin": "ut_martin",
  "Utah State": "utah_state",
  "Utah Tech": "utah_tech",
  "Utah": "utah",
  "UTEP": "utep",
  "UTSA": "utsa",
  "Valparaiso": "valparaiso",
  "Vanderbilt": "vanderbilt",
  "Villanova": "villanova",
  "Virginia Tech": "virginia_tech",
  "Virginia": "virginia",
  "VMI": "vmi",
  "W Carolina": "w_carolina",
  "W Illinois": "w_illinois",
  "W Michigan": "w_michigan",
  "Wagner": "wagner",
  "Wake Forest": "wake_forest",
  "Washington St": "washington_st",
  "Washington": "washington",
  "Weber St": "weber_st",
  "West Georgia": "west_georgia",
  "West Virginia": "west_virginia",
  "Western KY": "western_ky",
  "William & Mary": "william_mary",
  "Wisconsin": "wisconsin",
  "Wofford": "wofford",
  "Wyoming": "wyoming",
  "Yale": "yale",
  "Youngstown St": "youngstown_st"
};

export const logoMap = {
  abilene_chrstn:      require('@/assets/teamLogos/abilene_chrstn.png'),
  air_force:           require('@/assets/teamLogos/air_force.png'),
  akron:               require('@/assets/teamLogos/akron.png'),
  alabama_am:          require('@/assets/teamLogos/alabama_am.png'),
  alabama_st:          require('@/assets/teamLogos/alabama_st.png'),
  alabama:             require('@/assets/teamLogos/alabama.png'),
  alcorn_st:           require('@/assets/teamLogos/alcorn_st.png'),
  app_state:           require('@/assets/teamLogos/app_state.png'),
  ar_pine_bluff:       require('@/assets/teamLogos/ar_pine_bluff.png'),
  arizona_st:          require('@/assets/teamLogos/arizona_st.png'),
  arizona:             require('@/assets/teamLogos/arizona.png'),
  arkansas_st:         require('@/assets/teamLogos/arkansas_st.png'),
  arkansas:            require('@/assets/teamLogos/arkansas.png'),
  army:                require('@/assets/teamLogos/army.png'),
  auburn:              require('@/assets/teamLogos/auburn.png'),
  austin_peay:         require('@/assets/teamLogos/austin_peay.png'),
  ball_state:          require('@/assets/teamLogos/ball_state.png'),
  baylor:              require('@/assets/teamLogos/baylor.png'),
  bethune:             require('@/assets/teamLogos/bethune.png'),
  boise_st:            require('@/assets/teamLogos/boise_st.png'),
  boston_college:      require('@/assets/teamLogos/boston_college.png'),
  bowling_green:       require('@/assets/teamLogos/bowling_green.png'),
  bryant:              require('@/assets/teamLogos/bryant.png'),
  brown:               require('@/assets/teamLogos/brown.png'),
  bucknell:            require('@/assets/teamLogos/bucknell.png'),
  buffalo:             require('@/assets/teamLogos/buffalo.png'),
  butler:              require('@/assets/teamLogos/butler.png'),
  byu:                 require('@/assets/teamLogos/byu.png'),
  c_arkansas:          require('@/assets/teamLogos/c_arkansas.png'),
  c_connecticut:       require('@/assets/teamLogos/c_connecticut.png'),
  c_michigan:          require('@/assets/teamLogos/c_michigan.png'),
  cal_poly:            require('@/assets/teamLogos/cal_poly.png'),
  california:          require('@/assets/teamLogos/california.png'),
  campbell:            require('@/assets/teamLogos/campbell.png'),
  charleston_so:       require('@/assets/teamLogos/charleston_so.png'),
  charlotte:           require('@/assets/teamLogos/charlotte.png'),
  chattanooga:         require('@/assets/teamLogos/chattanooga.png'),
  cincinnati:          require('@/assets/teamLogos/cincinnati.png'),
  clemson:             require('@/assets/teamLogos/clemson.png'),
  coastal:         require('@/assets/teamLogos/coastal.png'),
  colgate:             require('@/assets/teamLogos/colgate.png'),
  colorado_st:         require('@/assets/teamLogos/colorado_st.png'),
  colorado:            require('@/assets/teamLogos/colorado.png'),
  columbia:            require('@/assets/teamLogos/columbia.png'),
  cornell:             require('@/assets/teamLogos/cornell.png'),
  dartmouth:           require('@/assets/teamLogos/dartmouth.png'),
  davidson:            require('@/assets/teamLogos/davidson.png'),
  dayton:              require('@/assets/teamLogos/dayton.png'),
  delaware_st:         require('@/assets/teamLogos/delaware_st.png'),
  delaware:            require('@/assets/teamLogos/delaware.png'),
  drake:               require('@/assets/teamLogos/drake.png'),
  duke:                require('@/assets/teamLogos/duke.png'),
  duquesne:            require('@/assets/teamLogos/duquesne.png'),
  e_illinois:          require('@/assets/teamLogos/e_illinois.png'),
  e_kentucky:          require('@/assets/teamLogos/e_kentucky.png'),
  e_michigan:          require('@/assets/teamLogos/e_michigan.png'),
  e_texas_am:          require('@/assets/teamLogos/e_texas_am.png'),
  e_washington:        require('@/assets/teamLogos/e_washington.png'),
  east_carolina:       require('@/assets/teamLogos/east_carolina.png'),
  elon:                require('@/assets/teamLogos/elon.png'),
  ETSU:                require('@/assets/teamLogos/ETSU.png'),
  fau:                 require('@/assets/teamLogos/fau.png'),
  fiu:                 require('@/assets/teamLogos/fiu.png'),
  florida_am:          require('@/assets/teamLogos/florida_am.png'),
  florida_st:          require('@/assets/teamLogos/florida_st.png'),
  florida:             require('@/assets/teamLogos/florida.png'),
  fordham:             require('@/assets/teamLogos/fordham.png'),
  fresno_st:           require('@/assets/teamLogos/fresno_st.png'),
  furman:              require('@/assets/teamLogos/furman.png'),
  ga_southern:         require('@/assets/teamLogos/ga_southern.png'),
  gardner_webb:        require('@/assets/teamLogos/gardner_webb.png'),
  georgetown:          require('@/assets/teamLogos/georgetown.png'),
  georgia_st:          require('@/assets/teamLogos/georgia_st.png'),
  georgia_tech:        require('@/assets/teamLogos/georgia_tech.png'),
  georgia:             require('@/assets/teamLogos/georgia.png'),
  grambling:           require('@/assets/teamLogos/grambling.png'),
  hampton:             require('@/assets/teamLogos/hampton.png'),
  harvard:             require('@/assets/teamLogos/harvard.png'),
  hawaii:              require('@/assets/teamLogos/hawaii.png'),
  holy_cross:          require('@/assets/teamLogos/holy_cross.png'),
  hou_christian:       require('@/assets/teamLogos/hou_christian.png'),
  houston:             require('@/assets/teamLogos/houston.png'),
  howard:              require('@/assets/teamLogos/howard.png'),
  idaho_st:            require('@/assets/teamLogos/idaho_st.png'),
  idaho:               require('@/assets/teamLogos/idaho.png'),
  illinois_st:         require('@/assets/teamLogos/illinois_st.png'),
  illinois:            require('@/assets/teamLogos/illinois.png'),
  incarnate_word:      require('@/assets/teamLogos/incarnate_word.png'),
  indiana_st:          require('@/assets/teamLogos/indiana_st.png'),
  indiana:             require('@/assets/teamLogos/indiana.png'),
  iowa_state:          require('@/assets/teamLogos/iowa_state.png'),
  iowa:                require('@/assets/teamLogos/iowa.png'),
  jackson_st:          require('@/assets/teamLogos/jackson_st.png'),
  james_madison:       require('@/assets/teamLogos/james_madison.png'),
  jax_state:           require('@/assets/teamLogos/jax_state.png'),
  kansas_st:           require('@/assets/teamLogos/kansas_st.png'),
  kansas:              require('@/assets/teamLogos/kansas.png'),
  kennesaw_st:         require('@/assets/teamLogos/kennesaw_st.png'),
  kent_state:          require('@/assets/teamLogos/kent_state.png'),
  kentucky:            require('@/assets/teamLogos/kentucky.png'),
  lafayette:           require('@/assets/teamLogos/lafayette.png'),
  lamar:               require('@/assets/teamLogos/lamar.png'),
  lehigh:              require('@/assets/teamLogos/lehigh.png'),
  liberty:             require('@/assets/teamLogos/liberty.png'),
  lindenwood:          require('@/assets/teamLogos/lindenwood.png'),
  long_island:         require('@/assets/teamLogos/long_island.png'),
  louisiana_tech:      require('@/assets/teamLogos/louisiana_tech.png'),
  louisiana:           require('@/assets/teamLogos/louisiana.png'),
  louisville:          require('@/assets/teamLogos/louisville.png'),
  lsu:                 require('@/assets/teamLogos/lsu.png'),
  maine:               require('@/assets/teamLogos/maine.png'),
  marist:              require('@/assets/teamLogos/marist.png'),
  marshall:            require('@/assets/teamLogos/marshall.png'),
  maryland:            require('@/assets/teamLogos/maryland.png'),
  mcneese:             require('@/assets/teamLogos/mcneese.png'),
  memphis:             require('@/assets/teamLogos/memphis.png'),
  mercer:              require('@/assets/teamLogos/mercer.png'),
  merrimack:           require('@/assets/teamLogos/merrimack.png'),
  miami:               require('@/assets/teamLogos/miami.png'),
  miami_oh:            require('@/assets/teamLogos/miami_oh.png'),
  michigan_st:         require('@/assets/teamLogos/michigan_st.png'),
  michigan:            require('@/assets/teamLogos/michigan.png'),
  minnesota:           require('@/assets/teamLogos/minnesota.png'),
  miss_valley_st:      require('@/assets/teamLogos/miss_valley_st.png'),
  mississippi_st:      require('@/assets/teamLogos/mississippi_st.png'),
  missouri_st:         require('@/assets/teamLogos/missouri_st.png'),
  missouri:            require('@/assets/teamLogos/missouri.png'),
  monmouth:            require('@/assets/teamLogos/monmouth.png'),
  montana_st:          require('@/assets/teamLogos/montana_st.png'),
  montana:             require('@/assets/teamLogos/montana.png'),
  morehead_st:         require('@/assets/teamLogos/morehead_st.png'),
  morgan_st:           require('@/assets/teamLogos/morgan_st.png'),
  mtsu:                require('@/assets/teamLogos/mtsu.png'),
  murray_st:           require('@/assets/teamLogos/murray_st.png'),
  n_arizona:           require('@/assets/teamLogos/n_arizona.png'),
  n_colorado:          require('@/assets/teamLogos/n_colorado.png'),
  n_dakota_st:         require('@/assets/teamLogos/n_dakota_st.png'),
  n_illinois:          require('@/assets/teamLogos/n_illinois.png'),
  navy:                require('@/assets/teamLogos/navy.png'),
  nc_at:               require('@/assets/teamLogos/nc_at.png'),
  nc_central:          require('@/assets/teamLogos/nc_central.png'),
  nc_state:            require('@/assets/teamLogos/nc_state.png'),
  nebraska:            require('@/assets/teamLogos/nebraska.png'),
  nevada:              require('@/assets/teamLogos/nevada.png'),
  new_hampshire:       require('@/assets/teamLogos/new_hampshire.png'),
  new_mexico:          require('@/assets/teamLogos/new_mexico.png'),
  new_mexico_st:       require('@/assets/teamLogos/new_mexico_st.png'),
  nicholls:            require('@/assets/teamLogos/nicholls.png'),
  norfolk_st:          require('@/assets/teamLogos/norfolk_st.png'),
  north_alabama:       require('@/assets/teamLogos/north_alabama.png'),
  north_carolina:      require('@/assets/teamLogos/north_carolina.png'),
  north_dakota:        require('@/assets/teamLogos/north_dakota.png'),
  north_texas:         require('@/assets/teamLogos/north_texas.png'),
  northern_iowa:       require('@/assets/teamLogos/northern_iowa.png'),
  northwestern:        require('@/assets/teamLogos/northwestern.png'),
  notre_dame:          require('@/assets/teamLogos/notre_dame.png'),
  nwestern_st:         require('@/assets/teamLogos/nwestern_st.png'),
  ohio:                require('@/assets/teamLogos/ohio.png'),
  ohio_state:          require('@/assets/teamLogos/ohio_state.png'),
  oklahoma_st:         require('@/assets/teamLogos/oklahoma_st.png'),
  oklahoma:            require('@/assets/teamLogos/oklahoma.png'),
  old_dominion:        require('@/assets/teamLogos/old_dominion.png'),
  ole_miss:            require('@/assets/teamLogos/ole_miss.png'),
  oregon_st:           require('@/assets/teamLogos/oregon_st.png'),
  oregon:              require('@/assets/teamLogos/oregon.png'),
  penn_state:          require('@/assets/teamLogos/penn_state.png'),
  penn:                require('@/assets/teamLogos/penn.png'),
  pitt:                require('@/assets/teamLogos/pitt.png'),
  portland_st:         require('@/assets/teamLogos/portland_st.png'),
  prairie_view:        require('@/assets/teamLogos/prairie_view.png'),
  presbyterian:        require('@/assets/teamLogos/presbyterian.png'),
  princeton:           require('@/assets/teamLogos/princeton.png'),
  purdue:              require('@/assets/teamLogos/purdue.png'),
  rhode_island:        require('@/assets/teamLogos/rhode_island.png'),
  rice:                require('@/assets/teamLogos/rice.png'),
  richmond:            require('@/assets/teamLogos/richmond.png'),
  robert_morris:       require('@/assets/teamLogos/robert_morris.png'),
  rutgers:             require('@/assets/teamLogos/rutgers.png'),
  s_illinois:          require('@/assets/teamLogos/s_illinois.png'),
  sacramento_st:       require('@/assets/teamLogos/sacramento_st.png'),
  sacred_heart:        require('@/assets/teamLogos/sacred_heart.png'),
  sam_houston:         require('@/assets/teamLogos/sam_houston.png'),
  samford:             require('@/assets/teamLogos/samford.png'),
  san_diego_st:        require('@/assets/teamLogos/san_diego_st.png'),
  san_diego:           require('@/assets/teamLogos/san_diego.png'),
  san_jose_st:         require('@/assets/teamLogos/san_jose_st.png'),
  sc_state:            require('@/assets/teamLogos/sc_state.png'),
  se_louisiana:        require('@/assets/teamLogos/se_louisiana.png'),
  se_missouri:         require('@/assets/teamLogos/se_missouri.png'),
  sf_austin:           require('@/assets/teamLogos/sf_austin.png'),
  smu:                 require('@/assets/teamLogos/smu.png'),
  south_alabama:       require('@/assets/teamLogos/south_alabama.png'),
  south_carolina:      require('@/assets/teamLogos/south_carolina.png'),
  s_dakota_st:         require('@/assets/teamLogos/s_dakota_st.png'),
  south_dakota:        require('@/assets/teamLogos/south_dakota.png'),
  south_florida:       require('@/assets/teamLogos/south_florida.png'),
  southern_miss:       require('@/assets/teamLogos/southern_miss.png'),
  southern_utah:       require('@/assets/teamLogos/southern_utah.png'),
  southern:            require('@/assets/teamLogos/southern.png'),
  st_francis_pa:       require('@/assets/teamLogos/st_francis_pa.png'),
  st_thomas_mn:        require('@/assets/teamLogos/st_thomas_mn.png'),
  stanford:            require('@/assets/teamLogos/stanford.png'),
  stetson:             require('@/assets/teamLogos/stetson.png'),
  stonehill:           require('@/assets/teamLogos/stonehill.png'),
  stony_brook:         require('@/assets/teamLogos/stony_brook.png'),
  syracuse:            require('@/assets/teamLogos/syracuse.png'),
  tarleton_st:         require('@/assets/teamLogos/tarleton_st.png'),
  tcu:                 require('@/assets/teamLogos/tcu.png'),
  temple:              require('@/assets/teamLogos/temple.png'),
  tennessee_st:        require('@/assets/teamLogos/tennessee_st.png'),
  tennessee_tech:      require('@/assets/teamLogos/tennessee_tech.png'),
  tennessee:           require('@/assets/teamLogos/tennessee.png'),
  texas_am:            require('@/assets/teamLogos/texas_am.png'),
  texas_southern:      require('@/assets/teamLogos/texas_southern.png'),
  texas_st:            require('@/assets/teamLogos/texas_st.png'),
  texas_tech:          require('@/assets/teamLogos/texas_tech.png'),
  texas:               require('@/assets/teamLogos/texas.png'),
  the_citadel:         require('@/assets/teamLogos/the_citadel.png'),
  toledo:              require('@/assets/teamLogos/toledo.png'),
  towson:              require('@/assets/teamLogos/towson.png'),
  troy:                require('@/assets/teamLogos/troy.png'),
  tulane:              require('@/assets/teamLogos/tulane.png'),
  tulsa:               require('@/assets/teamLogos/tulsa.png'),
  uab:                 require('@/assets/teamLogos/uab.png'),
  ualbany:             require('@/assets/teamLogos/ualbany.png'),
  uc_davis:            require('@/assets/teamLogos/uc_davis.png'),
  ucf:                 require('@/assets/teamLogos/ucf.png'),
  ucla:                require('@/assets/teamLogos/ucla.png'),
  uconn:               require('@/assets/teamLogos/uconn.png'),
  ul_monroe:           require('@/assets/teamLogos/ul_monroe.png'),
  umass:               require('@/assets/teamLogos/umass.png'),
  unlv:                require('@/assets/teamLogos/unlv.png'),
  usc:                 require('@/assets/teamLogos/usc.png'),
  ut_martin:           require('@/assets/teamLogos/ut_martin.png'),
  utah_state:          require('@/assets/teamLogos/utah_state.png'),
  utah_tech:           require('@/assets/teamLogos/utah_tech.png'),
  utah:                require('@/assets/teamLogos/utah.png'),
  utep:                require('@/assets/teamLogos/utep.png'),
  utsa:                require('@/assets/teamLogos/utsa.png'),
  valparaiso:          require('@/assets/teamLogos/valparaiso.png'),
  vanderbilt:          require('@/assets/teamLogos/vanderbilt.png'),
  villanova:           require('@/assets/teamLogos/villanova.png'),
  virginia_tech:       require('@/assets/teamLogos/virginia_tech.png'),
  virginia:            require('@/assets/teamLogos/virginia.png'),
  vmi:                 require('@/assets/teamLogos/vmi.png'),
  w_carolina:          require('@/assets/teamLogos/w_carolina.png'),
  w_illinois:          require('@/assets/teamLogos/w_illinois.png'),
  w_michigan:          require('@/assets/teamLogos/w_michigan.png'),
  wagner:              require('@/assets/teamLogos/wagner.png'),
  wake_forest:         require('@/assets/teamLogos/wake_forest.png'),
  washington_st:       require('@/assets/teamLogos/washington_st.png'),
  washington:          require('@/assets/teamLogos/washington.png'),
  weber_st:            require('@/assets/teamLogos/weber_st.png'),
  west_georgia:        require('@/assets/teamLogos/west_georgia.png'),
  west_virginia:       require('@/assets/teamLogos/west_virginia.png'),
  western_ky:          require('@/assets/teamLogos/western_ky.png'),
  william_mary:        require('@/assets/teamLogos/william_mary.png'),
  wisconsin:           require('@/assets/teamLogos/wisconsin.png'),
  wofford:             require('@/assets/teamLogos/wofford.png'),
  wyoming:             require('@/assets/teamLogos/wyoming.png'),
  yale:                require('@/assets/teamLogos/yale.png'),
  youngstown_st:       require('@/assets/teamLogos/youngstown_st.png'),
};